// DirStatsTUIVersion.hpp
// Generated by CMake

namespace DirStatsTUI
{
const int32_t CM_VERSION_MAJOR = @DirStatsTUI_VERSION_MAJOR@;
const int32_t CM_VERSION_MINOR = @DirStatsTUI_VERSION_MINOR@;
const int32_t CM_VERSION_PATCH = @DirStatsTUI_VERSION_PATCH@;
const std::string CM_VERSION_STRING = "v@DirStatsTUI_VERSION@";

const std::string CM_APP_CMAKE_NAME = "@PROJECT_NAME@";
const std::string CM_APP_CMAKE_DESCRIPTION = "@DirStatsTUI_DESCRIPTION@";
};
