// ProjectVersion.hpp
// Generated by CMake

namespace Project
{
const int32_t CM_VERSION_MAJOR = @Project_VERSION_MAJOR@;
const int32_t CM_VERSION_MINOR = @Project_VERSION_MINOR@;
const int32_t CM_VERSION_PATCH = @Project_VERSION_PATCH@;
const std::string CM_VERSION_STRING = "v@Project_VERSION@";

const std::string CM_APP_CMAKE_NAME = "@PROJECT_NAME@";
const std::string CM_APP_CMAKE_DESCRIPTION = "@HashMe_DESCRIPTION@";
};
